// <auto-generated />
#pragma warning disable 1570, 1591

using System;
using Microsoft.ML.Probabilistic;
using Microsoft.ML.Probabilistic.Distributions;
using Microsoft.ML.Probabilistic.Factors;
using Microsoft.ML.Probabilistic.Collections;

namespace Models
{
	/// <summary>
	/// Generated algorithm for performing inference.
	/// </summary>
	/// <remarks>
	/// If you wish to use this class directly, you must perform the following steps:
	/// 1) Create an instance of the class.
	/// 2) Set the value of any externally-set fields e.g. data, priors.
	/// 3) Call the Execute(numberOfIterations) method.
	/// 4) Use the XXXMarginal() methods to retrieve posterior marginals for different variables.
	/// 
	/// Generated by Infer.NET 0.3.1810.501 at 6:38 PM on Saturday, October 26, 2019.
	/// </remarks>
	public partial class Model_EP : IGeneratedAlgorithm
	{
		#region Fields
		/// <summary>True if Changed_vbool__0 has executed. Set this to false to force re-execution of Changed_vbool__0</summary>
		public bool Changed_vbool__0_isDone;
		/// <summary>True if Changed_vbool__0_vbool__1 has executed. Set this to false to force re-execution of Changed_vbool__0_vbool__1</summary>
		public bool Changed_vbool__0_vbool__1_isDone;
		/// <summary>True if Changed_vbool__1 has executed. Set this to false to force re-execution of Changed_vbool__1</summary>
		public bool Changed_vbool__1_isDone;
		/// <summary>Field backing the NumberOfIterationsDone property</summary>
		private int numberOfIterationsDone;
		/// <summary>Field backing the vbool__0 property</summary>
		private bool[] Vbool__0;
		public DistributionStructArray<Bernoulli,bool> vbool__0_marginal;
		/// <summary>Field backing the vbool__1 property</summary>
		private bool[] Vbool__1;
		public DistributionStructArray<Bernoulli,bool> vbool__1_marginal;
		/// <summary>Message to marginal of 'vbool2'</summary>
		public Bernoulli vbool2_marginal_F;
		/// <summary>Message to marginal of 'vdouble0'</summary>
		public Beta vdouble0_marginal_F;
		/// <summary>Message to marginal of 'vdouble1'</summary>
		public Beta vdouble1_marginal_F;
		/// <summary>Message to marginal of 'vdouble2'</summary>
		public Beta vdouble2_marginal_F;
		#endregion

		#region Properties
		/// <summary>The number of iterations done from the initial state</summary>
		public int NumberOfIterationsDone
		{
			get {
				return this.numberOfIterationsDone;
			}
		}

		/// <summary>The externally-specified value of 'vbool__0'</summary>
		public bool[] vbool__0
		{
			get {
				return this.Vbool__0;
			}
			set {
				if ((value!=null)&&(value.Length!=5)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+5)+" was expected for variable \'vbool__0\'");
				}
				this.Vbool__0 = value;
				this.numberOfIterationsDone = 0;
				this.Changed_vbool__0_vbool__1_isDone = false;
				this.Changed_vbool__0_isDone = false;
			}
		}

		/// <summary>The externally-specified value of 'vbool__1'</summary>
		public bool[] vbool__1
		{
			get {
				return this.Vbool__1;
			}
			set {
				if ((value!=null)&&(value.Length!=5)) {
					throw new ArgumentException(((("Provided array of length "+value.Length)+" when length ")+5)+" was expected for variable \'vbool__1\'");
				}
				this.Vbool__1 = value;
				this.numberOfIterationsDone = 0;
				this.Changed_vbool__0_vbool__1_isDone = false;
				this.Changed_vbool__1_isDone = false;
			}
		}

		#endregion

		#region Methods
		/// <summary>Computations that depend on the observed value of vbool__0</summary>
		private void Changed_vbool__0()
		{
			if (this.Changed_vbool__0_isDone) {
				return ;
			}
			this.vbool__0_marginal = new DistributionStructArray<Bernoulli,bool>(5, delegate(int index0) {
				return Bernoulli.Uniform();
			});
			this.vbool__0_marginal = Distribution.SetPoint<DistributionStructArray<Bernoulli,bool>,bool[]>(this.vbool__0_marginal, this.Vbool__0);
			this.Changed_vbool__0_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of vbool__0 and vbool__1</summary>
		private void Changed_vbool__0_vbool__1()
		{
			if (this.Changed_vbool__0_vbool__1_isDone) {
				return ;
			}
			Bernoulli vBernoulli0 = Bernoulli.Uniform();
			this.vbool2_marginal_F = Bernoulli.Uniform();
			DistributionStructArray<Bernoulli,bool> vbool2_selector_cases_B;
			// Create array for 'vbool2_selector_cases' Backwards messages.
			vbool2_selector_cases_B = new DistributionStructArray<Bernoulli,bool>(2);
			for(int _ind0 = 0; _ind0<2; _ind0++) {
				vbool2_selector_cases_B[_ind0] = Bernoulli.Uniform();
			}
			Bernoulli[] vbool2_selector_cases_0_uses_B;
			// Create array for 'vbool2_selector_cases_0_uses' Backwards messages.
			vbool2_selector_cases_0_uses_B = new Bernoulli[16];
			vbool2_selector_cases_0_uses_B[14] = Bernoulli.Uniform();
			vbool2_selector_cases_0_uses_B[11] = Bernoulli.Uniform();
			vbool2_selector_cases_0_uses_B[9] = Bernoulli.Uniform();
			vbool2_selector_cases_0_uses_B[8] = Bernoulli.Uniform();
			vbool2_selector_cases_0_uses_B[7] = Bernoulli.Uniform();
			vbool2_selector_cases_0_uses_B[6] = Bernoulli.Uniform();
			vbool2_selector_cases_0_uses_B[5] = Bernoulli.Uniform();
			vbool2_selector_cases_0_uses_B[4] = Bernoulli.Uniform();
			vbool2_selector_cases_0_uses_B[3] = Bernoulli.Uniform();
			vbool2_selector_cases_0_uses_B[2] = Bernoulli.Uniform();
			vbool2_selector_cases_0_uses_B[1] = Bernoulli.Uniform();
			vbool2_selector_cases_0_uses_B[0] = Bernoulli.Uniform();
			Beta vBeta0 = Beta.Uniform();
			DistributionStructArray<Beta,double> vdouble0_rep_B;
			// Create array for 'vdouble0_rep' Backwards messages.
			vdouble0_rep_B = new DistributionStructArray<Beta,double>(5);
			for(int index0 = 0; index0<5; index0++) {
				vdouble0_rep_B[index0] = Beta.Uniform();
				// Message to 'vdouble0_rep' from Bernoulli factor
				vdouble0_rep_B[index0] = BernoulliFromBetaOp.ProbTrueAverageConditional(this.Vbool__0[index0]);
			}
			Beta vdouble0_rep_B_toDef;
			// Message to 'vdouble0_rep' from Replicate factor
			vdouble0_rep_B_toDef = ReplicateOp_Divide.ToDefInit<Beta>(vBeta0);
			// Message to 'vdouble0_rep' from Replicate factor
			vdouble0_rep_B_toDef = ReplicateOp_Divide.ToDef<Beta>(vdouble0_rep_B, vdouble0_rep_B_toDef);
			Beta vdouble0_rep_F_marginal;
			// Message to 'vdouble0_rep' from Replicate factor
			vdouble0_rep_F_marginal = ReplicateOp_Divide.MarginalInit<Beta>(vBeta0);
			// Message to 'vdouble0_rep' from Replicate factor
			vdouble0_rep_F_marginal = ReplicateOp_Divide.Marginal<Beta>(vdouble0_rep_B_toDef, vBeta0, vdouble0_rep_F_marginal);
			DistributionStructArray<Beta,double> vdouble0_rep_F;
			// Create array for 'vdouble0_rep' Forwards messages.
			vdouble0_rep_F = new DistributionStructArray<Beta,double>(5);
			for(int index0 = 0; index0<5; index0++) {
				vdouble0_rep_F[index0] = Beta.Uniform();
				// Message to 'vdouble0_rep' from Replicate factor
				vdouble0_rep_F[index0] = ReplicateOp_Divide.UsesAverageConditional<Beta>(vdouble0_rep_B[index0], vdouble0_rep_F_marginal, index0, vdouble0_rep_F[index0]);
			}
			DistributionStructArray<Bernoulli,bool> vbool2_selector_cases_0_rep_B;
			// Create array for 'vbool2_selector_cases_0_rep' Backwards messages.
			vbool2_selector_cases_0_rep_B = new DistributionStructArray<Bernoulli,bool>(5);
			for(int index0 = 0; index0<5; index0++) {
				vbool2_selector_cases_0_rep_B[index0] = Bernoulli.Uniform();
				// Message to 'vbool2_selector_cases_0_rep' from Bernoulli factor
				vbool2_selector_cases_0_rep_B[index0] = Bernoulli.FromLogOdds(BernoulliFromBetaOp.LogEvidenceRatio(this.Vbool__0[index0], vdouble0_rep_F[index0]));
			}
			vbool2_selector_cases_0_uses_B[10] = Bernoulli.Uniform();
			// Message to 'vbool2_selector_cases_0_uses' from Replicate factor
			vbool2_selector_cases_0_uses_B[10] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(vbool2_selector_cases_0_rep_B, vbool2_selector_cases_0_uses_B[10]);
			vbool2_selector_cases_0_uses_B[12] = Bernoulli.Uniform();
			// Message to 'vbool2_selector_cases_0_uses' from Replicate factor
			vbool2_selector_cases_0_uses_B[12] = Bernoulli.FromLogOdds(ReplicateOp.LogEvidenceRatio<Beta>(vdouble0_rep_B, vBeta0, vdouble0_rep_F));
			DistributionStructArray<Beta,double> vdouble1_rep_B;
			// Create array for 'vdouble1_rep' Backwards messages.
			vdouble1_rep_B = new DistributionStructArray<Beta,double>(5);
			for(int index1 = 0; index1<5; index1++) {
				vdouble1_rep_B[index1] = Beta.Uniform();
				// Message to 'vdouble1_rep' from Bernoulli factor
				vdouble1_rep_B[index1] = BernoulliFromBetaOp.ProbTrueAverageConditional(this.Vbool__1[index1]);
			}
			Beta vdouble1_rep_B_toDef;
			// Message to 'vdouble1_rep' from Replicate factor
			vdouble1_rep_B_toDef = ReplicateOp_Divide.ToDefInit<Beta>(vBeta0);
			// Message to 'vdouble1_rep' from Replicate factor
			vdouble1_rep_B_toDef = ReplicateOp_Divide.ToDef<Beta>(vdouble1_rep_B, vdouble1_rep_B_toDef);
			Beta vdouble1_rep_F_marginal;
			// Message to 'vdouble1_rep' from Replicate factor
			vdouble1_rep_F_marginal = ReplicateOp_Divide.MarginalInit<Beta>(vBeta0);
			// Message to 'vdouble1_rep' from Replicate factor
			vdouble1_rep_F_marginal = ReplicateOp_Divide.Marginal<Beta>(vdouble1_rep_B_toDef, vBeta0, vdouble1_rep_F_marginal);
			DistributionStructArray<Beta,double> vdouble1_rep_F;
			// Create array for 'vdouble1_rep' Forwards messages.
			vdouble1_rep_F = new DistributionStructArray<Beta,double>(5);
			for(int index1 = 0; index1<5; index1++) {
				vdouble1_rep_F[index1] = Beta.Uniform();
				// Message to 'vdouble1_rep' from Replicate factor
				vdouble1_rep_F[index1] = ReplicateOp_Divide.UsesAverageConditional<Beta>(vdouble1_rep_B[index1], vdouble1_rep_F_marginal, index1, vdouble1_rep_F[index1]);
			}
			DistributionStructArray<Bernoulli,bool> vbool2_selector_cases_0_rep2_B;
			// Create array for 'vbool2_selector_cases_0_rep2' Backwards messages.
			vbool2_selector_cases_0_rep2_B = new DistributionStructArray<Bernoulli,bool>(5);
			for(int index1 = 0; index1<5; index1++) {
				vbool2_selector_cases_0_rep2_B[index1] = Bernoulli.Uniform();
				// Message to 'vbool2_selector_cases_0_rep2' from Bernoulli factor
				vbool2_selector_cases_0_rep2_B[index1] = Bernoulli.FromLogOdds(BernoulliFromBetaOp.LogEvidenceRatio(this.Vbool__1[index1], vdouble1_rep_F[index1]));
			}
			vbool2_selector_cases_0_uses_B[13] = Bernoulli.Uniform();
			// Message to 'vbool2_selector_cases_0_uses' from Replicate factor
			vbool2_selector_cases_0_uses_B[13] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(vbool2_selector_cases_0_rep2_B, vbool2_selector_cases_0_uses_B[13]);
			vbool2_selector_cases_0_uses_B[15] = Bernoulli.Uniform();
			// Message to 'vbool2_selector_cases_0_uses' from Replicate factor
			vbool2_selector_cases_0_uses_B[15] = Bernoulli.FromLogOdds(ReplicateOp.LogEvidenceRatio<Beta>(vdouble1_rep_B, vBeta0, vdouble1_rep_F));
			Bernoulli vbool2_selector_cases_0_B = Bernoulli.Uniform();
			// Message to 'vbool2_selector_cases_0' from Replicate factor
			vbool2_selector_cases_0_B = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(vbool2_selector_cases_0_uses_B, vbool2_selector_cases_0_B);
			// Message to 'vbool2_selector_cases' from Copy factor
			vbool2_selector_cases_B[0] = ArrayHelper.SetTo<Bernoulli>(vbool2_selector_cases_B[0], vbool2_selector_cases_0_B);
			Bernoulli[] vbool2_selector_cases_1_uses_B;
			// Create array for 'vbool2_selector_cases_1_uses' Backwards messages.
			vbool2_selector_cases_1_uses_B = new Bernoulli[13];
			vbool2_selector_cases_1_uses_B[11] = Bernoulli.Uniform();
			vbool2_selector_cases_1_uses_B[8] = Bernoulli.Uniform();
			vbool2_selector_cases_1_uses_B[5] = Bernoulli.Uniform();
			vbool2_selector_cases_1_uses_B[4] = Bernoulli.Uniform();
			vbool2_selector_cases_1_uses_B[3] = Bernoulli.Uniform();
			vbool2_selector_cases_1_uses_B[2] = Bernoulli.Uniform();
			vbool2_selector_cases_1_uses_B[1] = Bernoulli.Uniform();
			vbool2_selector_cases_1_uses_B[0] = Bernoulli.Uniform();
			DistributionStructArray<Beta,double> vdouble2_rep2_B;
			// Create array for 'vdouble2_rep2' Backwards messages.
			vdouble2_rep2_B = new DistributionStructArray<Beta,double>(5);
			for(int index1 = 0; index1<5; index1++) {
				vdouble2_rep2_B[index1] = Beta.Uniform();
				// Message to 'vdouble2_rep2' from Bernoulli factor
				vdouble2_rep2_B[index1] = BernoulliFromBetaOp.ProbTrueAverageConditional(this.Vbool__1[index1]);
			}
			Beta[] vdouble2_uses_F;
			// Create array for 'vdouble2_uses' Forwards messages.
			vdouble2_uses_F = new Beta[2];
			vdouble2_uses_F[1] = Beta.Uniform();
			Beta vdouble2_rep2_B_toDef;
			// Message to 'vdouble2_rep2' from Replicate factor
			vdouble2_rep2_B_toDef = ReplicateOp_Divide.ToDefInit<Beta>(vdouble2_uses_F[1]);
			// Message to 'vdouble2_rep2' from Replicate factor
			vdouble2_rep2_B_toDef = ReplicateOp_Divide.ToDef<Beta>(vdouble2_rep2_B, vdouble2_rep2_B_toDef);
			Beta[] vdouble2_uses_B;
			// Create array for 'vdouble2_uses' Backwards messages.
			vdouble2_uses_B = new Beta[2];
			vdouble2_uses_B[1] = Beta.Uniform();
			// Message to 'vdouble2_uses' from Replicate factor
			vdouble2_uses_B[1] = ArrayHelper.SetTo<Beta>(vdouble2_uses_B[1], vdouble2_rep2_B_toDef);
			vdouble2_uses_F[0] = Beta.Uniform();
			Beta vdouble2_rep_F_marginal;
			// Message to 'vdouble2_rep' from Replicate factor
			vdouble2_rep_F_marginal = ReplicateOp_Divide.MarginalInit<Beta>(vdouble2_uses_F[0]);
			Beta vdouble2_rep_B_toDef;
			// Message to 'vdouble2_rep' from Replicate factor
			vdouble2_rep_B_toDef = ReplicateOp_Divide.ToDefInit<Beta>(vdouble2_uses_F[0]);
			// Message to 'vdouble2_uses' from Replicate factor
			vdouble2_uses_F[0] = ReplicateOp_NoDivide.UsesAverageConditional<Beta>(vdouble2_uses_B, vBeta0, 0, vdouble2_uses_F[0]);
			DistributionStructArray<Beta,double> vdouble2_rep_B;
			// Create array for 'vdouble2_rep' Backwards messages.
			vdouble2_rep_B = new DistributionStructArray<Beta,double>(5);
			for(int index0 = 0; index0<5; index0++) {
				vdouble2_rep_B[index0] = Beta.Uniform();
				// Message to 'vdouble2_rep' from Bernoulli factor
				vdouble2_rep_B[index0] = BernoulliFromBetaOp.ProbTrueAverageConditional(this.Vbool__0[index0]);
			}
			// Message to 'vdouble2_rep' from Replicate factor
			vdouble2_rep_B_toDef = ReplicateOp_Divide.ToDef<Beta>(vdouble2_rep_B, vdouble2_rep_B_toDef);
			vdouble2_uses_B[0] = Beta.Uniform();
			// Message to 'vdouble2_uses' from Replicate factor
			vdouble2_uses_B[0] = ArrayHelper.SetTo<Beta>(vdouble2_uses_B[0], vdouble2_rep_B_toDef);
			Beta vdouble2_rep2_F_marginal;
			// Message to 'vdouble2_rep2' from Replicate factor
			vdouble2_rep2_F_marginal = ReplicateOp_Divide.MarginalInit<Beta>(vdouble2_uses_F[1]);
			// Message to 'vdouble2_uses' from Replicate factor
			vdouble2_uses_F[1] = ReplicateOp_NoDivide.UsesAverageConditional<Beta>(vdouble2_uses_B, vBeta0, 1, vdouble2_uses_F[1]);
			vbool2_selector_cases_1_uses_B[6] = Bernoulli.Uniform();
			// Message to 'vbool2_selector_cases_1_uses' from Replicate factor
			vbool2_selector_cases_1_uses_B[6] = Bernoulli.FromLogOdds(ReplicateOp.LogEvidenceRatio<Beta>(vdouble2_uses_B, vBeta0, vdouble2_uses_F));
			// Message to 'vdouble2_rep' from Replicate factor
			vdouble2_rep_F_marginal = ReplicateOp_Divide.Marginal<Beta>(vdouble2_rep_B_toDef, vdouble2_uses_F[0], vdouble2_rep_F_marginal);
			DistributionStructArray<Beta,double> vdouble2_rep_F;
			// Create array for 'vdouble2_rep' Forwards messages.
			vdouble2_rep_F = new DistributionStructArray<Beta,double>(5);
			for(int index0 = 0; index0<5; index0++) {
				vdouble2_rep_F[index0] = Beta.Uniform();
				// Message to 'vdouble2_rep' from Replicate factor
				vdouble2_rep_F[index0] = ReplicateOp_Divide.UsesAverageConditional<Beta>(vdouble2_rep_B[index0], vdouble2_rep_F_marginal, index0, vdouble2_rep_F[index0]);
			}
			DistributionStructArray<Bernoulli,bool> vbool2_selector_cases_1_rep_B;
			// Create array for 'vbool2_selector_cases_1_rep' Backwards messages.
			vbool2_selector_cases_1_rep_B = new DistributionStructArray<Bernoulli,bool>(5);
			for(int index0 = 0; index0<5; index0++) {
				vbool2_selector_cases_1_rep_B[index0] = Bernoulli.Uniform();
				// Message to 'vbool2_selector_cases_1_rep' from Bernoulli factor
				vbool2_selector_cases_1_rep_B[index0] = Bernoulli.FromLogOdds(BernoulliFromBetaOp.LogEvidenceRatio(this.Vbool__0[index0], vdouble2_rep_F[index0]));
			}
			vbool2_selector_cases_1_uses_B[7] = Bernoulli.Uniform();
			// Message to 'vbool2_selector_cases_1_uses' from Replicate factor
			vbool2_selector_cases_1_uses_B[7] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(vbool2_selector_cases_1_rep_B, vbool2_selector_cases_1_uses_B[7]);
			vbool2_selector_cases_1_uses_B[9] = Bernoulli.Uniform();
			// Message to 'vbool2_selector_cases_1_uses' from Replicate factor
			vbool2_selector_cases_1_uses_B[9] = Bernoulli.FromLogOdds(ReplicateOp.LogEvidenceRatio<Beta>(vdouble2_rep_B, vdouble2_uses_F[0], vdouble2_rep_F));
			// Message to 'vdouble2_rep2' from Replicate factor
			vdouble2_rep2_F_marginal = ReplicateOp_Divide.Marginal<Beta>(vdouble2_rep2_B_toDef, vdouble2_uses_F[1], vdouble2_rep2_F_marginal);
			DistributionStructArray<Beta,double> vdouble2_rep2_F;
			// Create array for 'vdouble2_rep2' Forwards messages.
			vdouble2_rep2_F = new DistributionStructArray<Beta,double>(5);
			for(int index1 = 0; index1<5; index1++) {
				vdouble2_rep2_F[index1] = Beta.Uniform();
				// Message to 'vdouble2_rep2' from Replicate factor
				vdouble2_rep2_F[index1] = ReplicateOp_Divide.UsesAverageConditional<Beta>(vdouble2_rep2_B[index1], vdouble2_rep2_F_marginal, index1, vdouble2_rep2_F[index1]);
			}
			DistributionStructArray<Bernoulli,bool> vbool2_selector_cases_1_rep2_B;
			// Create array for 'vbool2_selector_cases_1_rep2' Backwards messages.
			vbool2_selector_cases_1_rep2_B = new DistributionStructArray<Bernoulli,bool>(5);
			for(int index1 = 0; index1<5; index1++) {
				vbool2_selector_cases_1_rep2_B[index1] = Bernoulli.Uniform();
				// Message to 'vbool2_selector_cases_1_rep2' from Bernoulli factor
				vbool2_selector_cases_1_rep2_B[index1] = Bernoulli.FromLogOdds(BernoulliFromBetaOp.LogEvidenceRatio(this.Vbool__1[index1], vdouble2_rep2_F[index1]));
			}
			vbool2_selector_cases_1_uses_B[10] = Bernoulli.Uniform();
			// Message to 'vbool2_selector_cases_1_uses' from Replicate factor
			vbool2_selector_cases_1_uses_B[10] = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(vbool2_selector_cases_1_rep2_B, vbool2_selector_cases_1_uses_B[10]);
			vbool2_selector_cases_1_uses_B[12] = Bernoulli.Uniform();
			// Message to 'vbool2_selector_cases_1_uses' from Replicate factor
			vbool2_selector_cases_1_uses_B[12] = Bernoulli.FromLogOdds(ReplicateOp.LogEvidenceRatio<Beta>(vdouble2_rep2_B, vdouble2_uses_F[1], vdouble2_rep2_F));
			Bernoulli vbool2_selector_cases_1_B = Bernoulli.Uniform();
			// Message to 'vbool2_selector_cases_1' from Replicate factor
			vbool2_selector_cases_1_B = ReplicateOp_NoDivide.DefAverageConditional<Bernoulli>(vbool2_selector_cases_1_uses_B, vbool2_selector_cases_1_B);
			// Message to 'vbool2_selector_cases' from Copy factor
			vbool2_selector_cases_B[1] = ArrayHelper.SetTo<Bernoulli>(vbool2_selector_cases_B[1], vbool2_selector_cases_1_B);
			Bernoulli vbool2_selector_B = default(Bernoulli);
			// Message to 'vbool2_selector' from Cases factor
			vbool2_selector_B = CasesOp.BAverageConditional(vbool2_selector_cases_B);
			// Message to 'vbool2_marginal' from Variable factor
			this.vbool2_marginal_F = VariableOp.MarginalAverageConditional<Bernoulli>(vbool2_selector_B, vBernoulli0, this.vbool2_marginal_F);
			this.vdouble0_marginal_F = Beta.Uniform();
			// Message to 'vdouble0_marginal' from Variable factor
			this.vdouble0_marginal_F = VariableOp.MarginalAverageConditional<Beta>(vdouble0_rep_B_toDef, vBeta0, this.vdouble0_marginal_F);
			this.vdouble1_marginal_F = Beta.Uniform();
			// Message to 'vdouble1_marginal' from Variable factor
			this.vdouble1_marginal_F = VariableOp.MarginalAverageConditional<Beta>(vdouble1_rep_B_toDef, vBeta0, this.vdouble1_marginal_F);
			this.vdouble2_marginal_F = Beta.Uniform();
			Beta vdouble2_use_B = Beta.Uniform();
			// Message to 'vdouble2_use' from Replicate factor
			vdouble2_use_B = ReplicateOp_NoDivide.DefAverageConditional<Beta>(vdouble2_uses_B, vdouble2_use_B);
			// Message to 'vdouble2_marginal' from Variable factor
			this.vdouble2_marginal_F = VariableOp.MarginalAverageConditional<Beta>(vdouble2_use_B, vBeta0, this.vdouble2_marginal_F);
			this.Changed_vbool__0_vbool__1_isDone = true;
		}

		/// <summary>Computations that depend on the observed value of vbool__1</summary>
		private void Changed_vbool__1()
		{
			if (this.Changed_vbool__1_isDone) {
				return ;
			}
			this.vbool__1_marginal = new DistributionStructArray<Bernoulli,bool>(5, delegate(int index1) {
				return Bernoulli.Uniform();
			});
			this.vbool__1_marginal = Distribution.SetPoint<DistributionStructArray<Bernoulli,bool>,bool[]>(this.vbool__1_marginal, this.Vbool__1);
			this.Changed_vbool__1_isDone = true;
		}

		/// <summary>Update all marginals, by iterating message passing the given number of times</summary>
		/// <param name="numberOfIterations">The number of times to iterate each loop</param>
		/// <param name="initialise">If true, messages that initialise loops are reset when observed values change</param>
		private void Execute(int numberOfIterations, bool initialise)
		{
			this.Changed_vbool__0_vbool__1();
			this.Changed_vbool__1();
			this.Changed_vbool__0();
			this.numberOfIterationsDone = numberOfIterations;
		}

		/// <summary>Update all marginals, by iterating message-passing the given number of times</summary>
		/// <param name="numberOfIterations">The total number of iterations that should be executed for the current set of observed values.  If this is more than the number already done, only the extra iterations are done.  If this is less than the number already done, message-passing is restarted from the beginning.  Changing the observed values resets the iteration count to 0.</param>
		public void Execute(int numberOfIterations)
		{
			this.Execute(numberOfIterations, true);
		}

		/// <summary>Get the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		public object GetObservedValue(string variableName)
		{
			if (variableName=="vbool__0") {
				return this.vbool__0;
			}
			if (variableName=="vbool__1") {
				return this.vbool__1;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName)
		{
			if (variableName=="vbool2") {
				return this.Vbool2Marginal();
			}
			if (variableName=="vdouble0") {
				return this.Vdouble0Marginal();
			}
			if (variableName=="vdouble1") {
				return this.Vdouble1Marginal();
			}
			if (variableName=="vdouble2") {
				return this.Vdouble2Marginal();
			}
			if (variableName=="vbool__1") {
				return this.Vbool__1Marginal();
			}
			if (variableName=="vbool__0") {
				return this.Vbool__0Marginal();
			}
			throw new ArgumentException("This class was not built to infer "+variableName);
		}

		/// <summary>Get the marginal distribution (computed up to this point) of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <returns>The marginal distribution computed up to this point</returns>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName));
		}

		/// <summary>Get the query-specific marginal distribution of a variable.</summary>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public object Marginal(string variableName, string query)
		{
			if (query=="Marginal") {
				return this.Marginal(variableName);
			}
			throw new ArgumentException(((("This class was not built to infer \'"+variableName)+"\' with query \'")+query)+"\'");
		}

		/// <summary>Get the query-specific marginal distribution of a variable, converted to type T</summary>
		/// <typeparam name="T">The distribution type.</typeparam>
		/// <param name="variableName">Name of the variable in the generated code</param>
		/// <param name="query">QueryType name. For example, GibbsSampling answers 'Marginal', 'Samples', and 'Conditionals' queries</param>
		/// <remarks>Execute, Update, or Reset must be called first to set the value of the marginal.</remarks>
		public T Marginal<T>(string variableName, string query)
		{
			return Distribution.ChangeType<T>(this.Marginal(variableName, query));
		}

		private void OnProgressChanged(ProgressChangedEventArgs e)
		{
			// Make a temporary copy of the event to avoid a race condition
			// if the last subscriber unsubscribes immediately after the null check and before the event is raised.
			EventHandler<ProgressChangedEventArgs> handler = this.ProgressChanged;
			if (handler!=null) {
				handler(this, e);
			}
		}

		/// <summary>Reset all messages to their initial values.  Sets NumberOfIterationsDone to 0.</summary>
		public void Reset()
		{
			this.Execute(0);
		}

		/// <summary>Set the observed value of the specified variable.</summary>
		/// <param name="variableName">Variable name</param>
		/// <param name="value">Observed value</param>
		public void SetObservedValue(string variableName, object value)
		{
			if (variableName=="vbool__0") {
				this.vbool__0 = (bool[])value;
				return ;
			}
			if (variableName=="vbool__1") {
				this.vbool__1 = (bool[])value;
				return ;
			}
			throw new ArgumentException("Not an observed variable name: "+variableName);
		}

		/// <summary>Update all marginals, by iterating message-passing an additional number of times</summary>
		/// <param name="additionalIterations">The number of iterations that should be executed, starting from the current message state.  Messages are not reset, even if observed values have changed.</param>
		public void Update(int additionalIterations)
		{
			this.Execute(checked(this.numberOfIterationsDone+additionalIterations), false);
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool__0' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Bernoulli,bool> Vbool__0Marginal()
		{
			return this.vbool__0_marginal;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool__1' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public DistributionStructArray<Bernoulli,bool> Vbool__1Marginal()
		{
			return this.vbool__1_marginal;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vbool2' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Bernoulli Vbool2Marginal()
		{
			return this.vbool2_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vdouble0' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Beta Vdouble0Marginal()
		{
			return this.vdouble0_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vdouble1' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Beta Vdouble1Marginal()
		{
			return this.vdouble1_marginal_F;
		}

		/// <summary>
		/// Returns the marginal distribution for 'vdouble2' given by the current state of the
		/// message passing algorithm.
		/// </summary>
		/// <returns>The marginal distribution</returns>
		public Beta Vdouble2Marginal()
		{
			return this.vdouble2_marginal_F;
		}

		#endregion

		#region Events
		/// <summary>Event that is fired when the progress of inference changes, typically at the end of one iteration of the inference algorithm.</summary>
		public event EventHandler<ProgressChangedEventArgs> ProgressChanged;
		#endregion

	}

}
